on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n nunu78 -g nunu788e78-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n nunu78 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n nunu78 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n nunu78 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: nunu78.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t nunu78.azurecr.io/slamapp:${{ github.sha }}
        docker push nunu78.azurecr.io/slamapp:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_slamapp_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep slamappb749 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace slamappb749`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: slamappb749
        container-registry-url: nunu78.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: slamappdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: slamappb749
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          nunu78.azurecr.io/slamapp:${{ github.sha }}
        imagepullsecrets: |
          slamappdockerauth